import { Outfit } from 'next/font/google';
import Nav from '@/components/Nav';
import { EntertainmentProvider } from './context/EntertainmentContext';
import './globals.css';

const outfit = Outfit({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-outfit',
});

export const metadata = {
  title: 'Entertainment Web',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} `}>
        <EntertainmentProvider>
          <Nav />
          {children}
        </EntertainmentProvider>
      </body>
    </html>
  );
}
